---
name: CD test

on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:

  deploy-dev:

    name: Deploy in the dev environment
    runs-on: ubuntu-latest
    steps:

      # Git Checkout
      - name: Check out argo repo
        uses: actions/checkout@v3
        with:
          repository: gitops-poc/argo
      - name: Test yq
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.spec.replicas' system-informer/base/deployment.yaml
