---
name: CD test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  deploy-dev:
    name: Deploy in the dev environment
    runs-on: ubuntu-latest
    env:
      ARGO_DIR: argo
    steps:
      # Git Checkout
      # - name: Check out argo repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: gitops-poc/argo
      - name: Add argo repo ssh key
        run: |
          mkdir $HOME/.ssh/
          ls -la $HOME
          echo "$SSH_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
        shell: bash
        env:
          SSH_KEY: ${{secrets.ARGO_SSH_KEY}}
      - name: Clone argo repo
        run: |
          git clone git@github.com:gitops-poc/argo.git $ARGO_DIR
      - name: Update dev image
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers.[0].image="ghcr.io/gitops-poc/systeminformer:test"' $ARGO_DIR/system-informer/overlays/dev/deployment.yaml
      - name: Output yaml to be applied
        working-directory: ${{ env.ARGO_DIR }}
        run: |
          kustomize build system-informer/overlays/dev
      # - name: Commit and push changes
      #   working-directory: $ARGO_DIR
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "ci: update dev image"
      #     git push
