---
name: CD test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  deploy-dev:
    name: Deploy in the dev environment
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      # - name: Check out argo repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: gitops-poc/argo
      - name: Clone repo
        run: |
          mkdir $HOME/.ssh/
          ls -la $HOME
          echo "$SSH_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          git clone git@github.com:gitops-poc/argo.git
          cd argo
          touch testfile
          git add testfile
          ls -la
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "testfile"
          git push
        shell: bash
        env:
          SSH_KEY: ${{secrets.ARGO_SSH_KEY}}
          
      # - name: Update dev image
      #   uses: mikefarah/yq@master
      #   with:
      #     cmd: yq -i '.spec.template.spec.containers.[0].image="ghcr.io/gitops-poc/systeminformer:test"' system-informer/overlays/dev/deployment.yaml
      # - name: Output result
      #   run: |
      #     cat system-informer/overlays/dev/deployment.yaml
