---
name: System-Informer master

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  codeql:
    uses: gitops-poc/workflows/.github/workflows/code-analysis.yml@master

  test:
    uses: gitops-poc/workflows/.github/workflows/gradle-tests.yml@master

  build-scan-push:
    needs: test
    permissions:
      checks: write
      pull-requests: write
      packages: write
      security-events: write
    uses: gitops-poc/workflows/.github/workflows/build-scan-push.yml@master
    with:
      image_tags: |
        type=raw,value={{sha}}
