---
name: System-Informer PR

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master
  push:

jobs:

  codeql:

    uses: gitops-poc/workflows/.github/workflows/code-analysis.yml@master

  mega-linter:

    uses: gitops-poc/workflows/.github/workflows/mega-linter.yml@master
    with:
      apply_fixes: "all"

  test-build-scan:

    name: Test, Build & Scan for CVEs
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:

      # Git Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gradle Unit Tests
        run: ./gradlew test

      # PPublishes the test results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        # Runs even if the tests fail
        if: always()
        with:
          files: "**/TEST-*.xml"

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub CR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/user/system-informer:pr-${{ github.sha }}

      - name: Scan for CVEs with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/gitops-poc/system-informer:pr-${{ github.sha }}
          format: github
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
