---
name: System-Informer PR

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:

  codeql:

    uses: gitops-poc/workflows/.github/workflows/code-analysis.yml@master

  mega-linter:

    uses: gitops-poc/workflows/.github/workflows/mega-linter.yml@master
    with:
      apply_fixes: "all"

  test:

    uses: gitops-poc/workflows/.github/workflows/gradle-tests.yml@master

  build-scan-push:

    needs: test
    permissions:
      checks: write
      pull-requests: write
      packages: write
      security-events: write

    uses: gitops-poc/workflows/.github/workflows/build-scan-push.yml@master
    with:
      image_tags: |
        type=raw,value=PR-{{date 'YYYYMMDD'}}-{{sha}}
